# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Dependencies
markdown:         redcarpet
highlighter:      rb-pygments

# Permalinks
permalink:        pretty

title:            'Ernesto''s Blog'
tagline:          'Ernesto''s Blog'
description:      'These are my experiences with new and current technology as well as my opinions on the future of software as a whole.'

email:            ernesto.blog@outlook.com
author:
  name:           'Ernesto Herrera'
  url:            'https://twitter.com/ernestolivelife'
mytheme:          'theme-base-08'
paginate:         1

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ernestolivelife
github_username:  ernestoherrera
github:           'https://github.com/ernestoherrera'
version:          '0.1'

# Build settings
markdown: kramdown
port:  8080

gems:
  - jekyll-paginate
  - jekyll-octicons

exclude:
  - Gemfile
  - Gemfile.lock
  - index.md